FROM apache/airflow:2.8.1-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
        default-jre-headless && \
    rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark==4.7.0 \
    apache-airflow-providers-postgres==5.10.0 \
    requests>=2.31.0 \
    psycopg2-binary>=2.9.0

COPY airflow/dags/ /opt/airflow/dags/
COPY DTM/ /opt/pipeline/DTM/
