global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "healthcare-pipeline"
    static_configs:
      - targets: ["pipeline:8000"]
        labels:
          service: "healthcare-etl"

  - job_name: "spark-metrics"
    metrics_path: "/metrics/prometheus"
    static_configs:
      - targets: ["spark-master:8080"]
        labels:
          service: "spark"

  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]
        labels:
          service: "kafka"

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          service: "postgresql"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          service: "infrastructure"
